accounts/urls.py
from django.urls import path
from .views import register, logout_user, login_user,password_reset
from django.contrib.auth import views
from .models import Customuser
app_name = "auth"

urlpatterns = [
    path('register/', register, name="register"),
    path('login/', login_user, name="login"),
    path('logout/', logout_user, name="logout"),
    path('password/reset/',views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),name="password_reset")
]

api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('geners/',GenreListCreateAPIView.as_view()),
    path('geners/<slug:slug>/', GenreRetirieveUPdateDeleteAPIView.as_view()),
    path('author/',AuthorListCreateAPIView.as_view()),
    path('book/<int:pk>/',BookRetireveUpdateDestroyAPIView.as_view()),
    path('author/<int:pk>/',AuyhorRetireveUpdateDestroyAPIView.as_view()),
    path('post/<int:pk>/',PostRetireveUpdateDestroyAPIView.as_view()),
    path('post/',PostListCreateAPIView.as_view()),
    path('auth/',ExampleAuthentication.as_view()),
    path('',BookListCreteAPIView.as_view()),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views #import this

urlpatterns = [
    path('api/v1/dj-rest-auth/',include('dj_rest_auth.urls') ),
    path('admin/', admin.site.urls),
    path('api/v1/',include('api.urls')),
    path('api/v1/registir/',include('dj_rest_auth.registration.urls')),
    path('main/', include('main.urls')),
    path('auth/', include('accounts.urls')),
    path('rest-auth', include('rest_framework.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),   
    path('', include('library.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,AbstractBaseUser, PermissionsMixin
from .managers import CustomUserManager
from django.utils import timezone

class Customuser(AbstractBaseUser,PermissionsMixin):
    GANDERS = [
        ('Male',' male'),
        ('Female',' Female'),
        ('Other',' Other'),
    ]
    username= models.CharField(max_length=255,null=True)
    full_name = models.CharField(max_length=255,blank=True)
    email =models.EmailField(unique=True)
    gander = models.CharField(max_length=10,choices=GANDERS,default=GANDERS[2])
    addres = models.CharField(max_length=255, null=True,blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()

    def __str__(self) -> str:
        return self.email

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Customuser


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = Customuser
        fields = ('email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

accounts/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth import login, logout, login, authenticate
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm,PasswordResetForm
from django.contrib.auth.models import User
from django.db.models.query_utils import Q
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from config import settings
from .models import Customuser


def register(request):
    form = NewUserForm()
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful")
            return redirect("list")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    return render(request, "accounts/register.html", {'form': form})

def login_user(request):
    form = AuthenticationForm()
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("list")
            else:
                messages.error(request,"Invalid username or password.")
        else:
            messages.error(request,"Invalid username or password.")
    return render(request, "accounts/login.html", {'form': form})


def logout_user(request):
    logout(request)
    messages.info(request, "You have successfully logged out.") 
    return redirect("list")


def password_reset(request):
    form = PasswordResetForm()
    if request.method == "POST":
        form =PasswordResetForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            users = Customuser.objects.filter(Q(email=email))
            if users.exists():
                for user in users:
                    subject = "Password Reset Requested"
                    email_template ="accounts/password_reset_text.txt"
                    context_data = {
                        "email" : user.email,
                        'domain':'127.0.0.1:8000',
					    'site_name': 'Website',
                        "user": user,
                        "protocol":"http",
                        "uid":urlsafe_base64_encode(force_bytes(user.pk)),
                        "Token": default_token_generator.make_token(user)
                    }
                    message =render_to_string(email_template,context_data)
                    try:
                        send_mail(subject, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse("Invalid header found.")
                    return redirect ("List")
            return render(request,"accounts/password_reset.html",{"form":form})

templates/accounts/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %} Login User {% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-3 my-5">
            <h1 class="text-center text-primary">Tizimga Kirish</h1>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <p style="float: left;"><a href="{% url 'auth:password_reset'%}" style="text-decoration: none" >Forgot password?</a></p>
                <button type="submit"style="float: right;" class="btn btn-primary">Kirish</button>   
    
            </form>

        </div>
    </div>
</div>
{% endblock content %}

templates/accounts/password_reset.html
{% extends 'base.html' %}


{% block content %}

	{% load crispy_forms_tags %}          

	<!--Reset Password-->
	<div class="container p-5">
  	 	<h2 class="font-weight-bold mt-3">Reset Password</h2>
		<hr>
		<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}                    
            <button class="btn btn-primary" type="submit">Send email</button>
        </form>
  	</div> 

{% endblock %}

templates/accounts/password_reset_complete.html
{% extends "base.html" %}

{% block content %} 
  
  <!--Password Reset Complete-->
    <div class="container p-4">
	    <h2 class="font-weight-bold mt-3">Password reset complete</h2>
		<hr>
        <p>Your password has been set. You may go ahead and log in now.</p>                 
        <a href="/login" class="btn btn-primary">Log in</a>
    </div>

{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}

  {% load crispy_forms_tags %}  
  
  <!--Password Reset Confirm-->
    <div class="container p-5">
	    <h2 class="font-weight-bold mt-3">Password Reset Confirm</h2>
		<hr>
        <p>Please enter your new password.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}                    
            <button class="btn btn-primary" type="submit">Reset password</button>
        </form>
    </div>

{% endblock %}

templates/accounts/password_reset_done.html
{% extends 'base.html' %}


{% block content %}

	<!--Password reset sent-->
	<div class="container p-5">
  	<h2 class="font-weight-bold mt-3">Password reset sent</h2>
		<hr>
		<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.<br>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
  </div>

{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %} Register User {% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-3 my-5">
            <h1 class="text-center text-primary">Registratsiya</h1>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Ro'yhatdan o'tish</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}