accounts/urls.py
from django.urls import path
from .views import register, logout_user, login_user,password_reset
from django.contrib.auth import views
from .models import Customuser
app_name = "auth"

urlpatterns = [
    path('register/', register, name="register"),
    path('login/', login_user, name="login"),
    path('logout/', logout_user, name="logout"),
    path('password/reset/',views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),name="password_reset")
]

api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('geners/',GenreListCreateAPIView.as_view()),
    path('geners/<slug:slug>/', GenreRetirieveUPdateDeleteAPIView.as_view()),
    path('author/',AuthorListCreateAPIView.as_view()),
    path('book/<int:pk>/',BookRetireveUpdateDestroyAPIView.as_view()),
    path('author/<int:pk>/',AuyhorRetireveUpdateDestroyAPIView.as_view()),
    path('post/<int:pk>/',PostRetireveUpdateDestroyAPIView.as_view()),
    path('post/',PostListCreateAPIView.as_view()),
    path('auth/',ExampleAuthentication.as_view()),
    path('',BookListCreteAPIView.as_view()),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views #import this

urlpatterns = [
    path('api/v1/dj-rest-auth/',include('dj_rest_auth.urls') ),
    path('admin/', admin.site.urls),
    path('api/v1/',include('api.urls')),
    path('api/v1/registir/',include('dj_rest_auth.registration.urls')),
    path('main/', include('main.urls')),
    path('auth/', include('accounts.urls')),
    path('rest-auth', include('rest_framework.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),   
    path('', include('library.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load author_tags %}
{% load genres_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}  {% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-dark navbar-expand-lg bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'list' %}">Asaxiy kitoblar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'list' %}">Barcha Kitoblar</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Mualliflar
                </a>
                <ul class="dropdown-menu">
                  {% authors as mualliflar %}
                  {% for muallif in mualliflar %}
                  <li><a class="dropdown-item" href="#">{{ muallif.full_name }}</a></li></li>
                  {% endfor %}
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Genres
                </a>
                <ul class="dropdown-menu">
                  {% genres as janrlar %}
                  {% for janr in janrlar %}
                  <li><a class="dropdown-item" href="#">{{ janr.name }}</a></li>
                  {% endfor %}
                </ul>
              </li>
              <li class="nav-item">
                {% if request.user.is_authenticated %}
                <a class="nav-link" href="{% url 'add_book' %}">Yangi kitob</a>
                {% endif %}
              </li>
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link disabled">{{ request.user }}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:logout' %}">Log Out</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:register' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:login' %}">Sign In</a>
              </li>
              {% endif %}
            </ul>
            <form class="d-flex" role="search" method="get">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
              <button class="btn btn-danger" type="submit">search</button>
            </form>
          </div>
        </div>
      </nav>
      {% include 'messages.html' %}

    {% block content %}

    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

templates/messages.html
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
    <strong>Message</strong> {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
</div>
{% endfor %}

templates/pagination.html
<div class="col-12">
    {% if page.has_other_pages %}
        <ul class="pagination justify-content-center">
            {% if page.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Prev</a>
                </li>
            {% endif %}
            {% for i in page.paginator.page_range %}
                {% if page.number == i %}
                    <li class="page-item active"><a class="page-link"><span>{{ i }}</span></a></li>
                {% else %}
                    <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">Next &raquo;</a>
                </li>
            {% endif %}
        </ul>
    {% endif %}
</div>