api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('geners/',GenreListCreateAPIView.as_view()),
    path('geners/<slug:slug>/', GenreRetirieveUPdateDeleteAPIView.as_view()),
    path('author/',AuthorListCreateAPIView.as_view()),
    path('book/<int:pk>/',BookRetireveUpdateDestroyAPIView.as_view()),
    path('author/<int:pk>/',AuyhorRetireveUpdateDestroyAPIView.as_view()),
    path('post/<int:pk>/',PostRetireveUpdateDestroyAPIView.as_view()),
    path('post/',PostListCreateAPIView.as_view()),
    path('auth/',ExampleAuthentication.as_view()),
    path('',BookListCreteAPIView.as_view()),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views #import this

urlpatterns = [
    path('api/v1/dj-rest-auth/',include('dj_rest_auth.urls') ),
    path('admin/', admin.site.urls),
    path('api/v1/',include('api.urls')),
    path('api/v1/registir/',include('dj_rest_auth.registration.urls')),
    path('main/', include('main.urls')),
    path('auth/', include('accounts.urls')),
    path('rest-auth', include('rest_framework.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),   
    path('', include('library.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.urls import path, re_path
from .views import *


urlpatterns = [
    path('', BooksListView.as_view(), name="list"),
    path('book/<int:pk>/', BookDetailView.as_view(), name="detail"),
    path('add/', BookCreateView.as_view(), name="add_book"),
    path('update/<int:pk>/', BookUpdateView.as_view(), name="update"),
    path('delete/<int:pk>/', BookDeleteView.as_view(), name="delete"),
    path('add/genre/', add_genres, name="add_genre"),
    path('add/author/', add_author, name="add_author"),
]

library/models.py
from django.db import models


class Genre(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    desc = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Author(models.Model):
    full_name = models.CharField(max_length=255)
    bio = models.TextField()
    image = models.ImageField(upload_to="authors")
    birth_date = models.DateField()
    death_date = models.DateField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.full_name


class Book(models.Model):
    title = models.CharField(max_length=255)
    desc = models.TextField()
    image = models.ImageField(upload_to="books")
    genres = models.ManyToManyField(Genre)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    stars = models.FloatField(verbose_name="Reyting")
    isbn_number = models.PositiveBigIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

library/forms.py
from django import forms
from .models import Book, Author


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"


class Genres(forms.Form):
    name = forms.CharField(max_length=100, required=True)
    slug = forms.SlugField(max_length=100, required=True)
    desc = forms.CharField(widget=forms.Textarea)


class AuthorForm(forms.ModelForm):
    check = forms.BooleanField(label="Married", initial=True)

    class Meta:
        model = Author
        fields = ('full_name', 'bio', 'image', 'check', 'birth_date', 'death_date')

        widgets = {
            "bio": forms.Textarea(attrs={
                "placeholder": "Muallifning hayoti"
            }),
            "birth_date": forms.DateInput(
                attrs={
                    "class": "form-control",
                    "type": "date"
                }
            ),
            "death_date": forms.DateInput(
                attrs={
                    "class": "form-control",
                    "type": "date"
                }
            )
        }

    

library/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from datetime import datetime
from .forms import BookForm, Genres, AuthorForm
from .models import Book, Genre, Author
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.db.models import Q

@login_required
def add_genres(request):
    form = Genres()
    if request.method == "POST":
        form = Genres(request.POST)
        if form.is_valid():
            Genre.objects.create(**form.cleaned_data)
            return redirect('list')
    return render(request, "library/add_genres.html", {'form': form})

@login_required
def add_author(request):
    form = AuthorForm()
    if request.method == "POST":
        form = AuthorForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('list')
    return render(request, "library/add_author.html", {"form": form})

# @login_required
def books_list(request):
    books = Book.objects.all().order_by('-created')
    paginator = Paginator(books,3)

    page = request.GET.get('page')
    try:
        books = paginator.page(page)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
      books  =  paginator.page(paginator.num_pages)  


    genres = Genre.objects.all()

    authors = Author.objects.all()
    return render(request, "library/index.html", {"books": books, 'genres': genres, 'authors': authors})




class BooksListView(ListView):
    model = Book
    context_object_name = "books"
    template_name = "library/index.html"
    paginate_by=3
   

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page = self.request.GET.get('page')
        search = self.request.GET.get('search')
        if search is not None:
            books = Book.objects.filter(
                Q(title__icontains=search) | Q(desc__icontains=search)
            ).order_by('-created')
        else:
            books = Book.objects.all().order_by('-created')
        paginator = Paginator(books,3)
        try:
            context['books'] = paginator.page(page)
        except PageNotAnInteger:
            context['books'] = paginator.page(1)
        except EmptyPage:
            context['books'] = paginator.page(paginator.num_pages)

        context['genres'] = Genre.objects.all()
        context['authors'] = Author.objects.all()
        return context


class BooksList(View):
    def get(self, request, *args, **kwargs):
        books = Book.objects.all().order_by('-created')
        genres = Genre.objects.all()
        authors = Author.objects.all()
        return render(request, "library/index.html", {"books": books, 'genres': genres, 'authors': authors})

    def post(self, request, *args, **kwargs):
        pass

@login_required
def book_detail(request, pk):
    book = Book.objects.get(id=pk)
    return render(request, "library/detail.html", {"book": book})


class BookDetailView(DetailView):
    model = Book
    template_name = "library/detail.html"
    context_object_name = "book"
    queryset = Book.objects.all()

   
class BookDetail(View):
    def get(self, request, pk, *args, **kwargs):
        book = Book.objects.get(id=pk)
        return render(request, "library/detail.html", {"book": book})

@login_required
def add_new_book(request):
    form = BookForm()

    if request.method == "POST":
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("list")

    return render(request, "library/add.html", {"form": form})

class AddBook(LoginRequiredMixin,View):
    template_name = "library/add.html"

    def get(self, request, *args, **kwargs):
        form = BookForm()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("list")
        else:
            return render(request, self.template_name, {"form": form})


class BookCreateView(LoginRequiredMixin,CreateView):
    model = Book
    template_name = "library/add.html"
    form_class = BookForm
    success_url = reverse_lazy("list")

@login_required
def update_book(request, pk):
    book = Book.objects.get(id=pk)
    form = BookForm(instance=book)

    if request.method == "POST":
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            # book.title = form.cleaned_data.get("title")
            # book.desc = form.cleaned_data.get('desc')
            # book.image = form.cleaned_data.get('image')
            # book.genres = form.cleaned_data.get('genres')
            # book.author = form.cleaned_data.get('author')
            # book.stars = form.cleaned_data.get('stars')
            # book.isbn_number = form.cleaned_data.get('isbn_number')
            # book.save()
            return redirect("list")

    return render(request, "library/edit.html", {"form": form})


class UpdateBook(LoginRequiredMixin,View):
    def get(self, request, pk, *args, **kwargs):
        book = Book.objects.get(id=pk)
        form = BookForm(instance=book)
        return render(request, "library/edit.html", {"form": form})

    def post(self, request, pk, *args, **kwargs):
        book = Book.objects.get(id=pk)
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            return redirect("list")

class BookUpdateView(LoginRequiredMixin,UpdateView):
    model = Book
    template_name = "library/edit.html"
    form_class = BookForm
    success_url = reverse_lazy("list")

@login_required
def delete_book(request, pk):
    book = get_object_or_404(Book, pk=pk)
    book.delete()
    return redirect("list")

class BookDeleteView(DeleteView):
    model = Book
    template_name = "library/delete.html"
    success_url = reverse_lazy("list")



class BookDelete(View):
    def get(self, request, pk, *args, **kwargs):
        book = get_object_or_404(Book, pk=pk)
        book.delete()
        return redirect("list")

templates/library/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Add New Book {% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-3 my-5">
            <h1 class="text-center text-primary">Yangi asar qo'shish</h1>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Saqlash</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/library/add_author.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %} Add New Author {% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-3 my-5">
            <h1 class="text-center text-primary">Yangi avtor qo'shish</h1>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Saqlash</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/library/add_genres.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Add New Genre {% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-3 my-5">
            <h1 class="text-center text-primary">Yangi janr qo'shish</h1>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Saqlash</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/library/delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Delete Book {% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-3 my-5">
            <h1 class="text-center text-primary">Asarni o'chirish</h1>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h3>Siz rostan ham bu kitobni o'chirmoqchimisiz?</h3>
                <button type="submit" class="btn btn-danger">O'chirish</button>
                <a href="{% url 'list' %}" class="btn btn-success">Orqaga</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/library/detail.html
{% extends 'base.html' %}

{% block title %} {{ book.title }} {% endblock title %}

{% block content %}
<div class="container my-5">
    <div class="row">
        <h1 class="text-center text-danger">{{ book.title }} ({{ book.stars }})</h1>
        <div class="col-md-4">
            {% if book.image %}
            <img src="{{ book.image.url }}" alt="" width="320" height="350">
            {% endif %}
            <ul class="list-group list-group-flush">
            {% for genre in book.genres.all %}
            <li class="list-group-item">{{ genre.name }}</li>
            {% endfor %}
            </ul>
        </div>
        <div class="col-md-8">
            <p>
                {{ book.desc }}
            </p>
            {% if request.user.is_authenticated %}
            <a href="{% url 'update' book.pk %}" class="btn btn-warning">Edit</a>
            <a href="{% url 'delete' book.pk %}" class="btn btn-danger">Delete</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/library/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Edit Book {% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-3 my-5">
            <h1 class="text-center text-primary">Asarni yangilash</h1>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Yangilash</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/library/index.html
{% extends 'base.html' %}

{% block title %} All Books {% endblock title %}

{% block content %}
<div class="container-fluid my-5">
    <div class="row">
        <div class="col-md-2 px-3">
            <h1 class="text-primary text-center">Mualliflar</h1>
            <ul class="list-group list-group-flush">
                {% for author in authors %}
                <li class="list-group-item">{{ author.full_name }}</li>
                {% endfor %}
            </ul>
            {% if request.user.is_authenticated %}
            <a href="{% url 'add_author' %}" class="btn btn-warning">Muallif qo'shish</a>
            {% endif %}
        </div>
        <div class="col-md-8">
            <h1 class="text-primary text-center">Barcha Asarlar</h1>
            <div class="container mt-4">
                <div class="row">
                    {% for book in books %}
                        <div class="col-md-4">
                            <div class="card mx-5" style="width: 18rem;">
                                {% if book.image %}
                                <img src="{{ book.image.url }}" class="card-img-top" height="300">
                                {% endif %}
                                <div class="card-body">
                                  <h5 class="card-title">{{ book.title }}</h5>
                                  <p class="card-text">{{ book.desc|truncatewords:20 }}</p>
                                  <a href="{% url 'detail' book.id %}" class="btn btn-primary">O'qish</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-2 px-5">
            <h1 class="text-primary text-center">Janrlar</h1>
            <ol class="list-group list-group-numbered">
                {% for genre in genres %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
                  <div class="ms-2 me-auto">
                    <div class="fw-bold">{{ genre.name }}</div>
                    {{ genre.desc }}
                  </div>
                  <span class="badge bg-primary rounded-pill">{{ genre.book_set.count }}</span>
                </li>
                {% endfor %}
                {% if request.user.is_authenticated %}

                <a href="{% url 'add_genre' %}" class="btn btn-primary">Janr qo'shish</a>
                {% endif %}
            </ol>
        </div>
    </div>
    {% include 'pagination.html' with page=books %}
</div>
{% endblock content %}